<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PCD2EDDG" failures="2" tests="4" name="Surefire test" time="7.842" errors="0" timestamp="2025-05-20T00:26:05 WIB">
  <testcase classname="com.example.api.ObjectTest" name="testAddAndDeleteObject" time="1.755">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.example.api.ObjectTest.testAddAndDeleteObject(ObjectTest.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testAddAndDeleteObject -->
  <testcase classname="com.example.api.ObjectTest" name="testAddObject" time="0.892"/>
  <testcase classname="com.example.api.ObjectTest" name="testDeleteObject" time="0.837">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.example.api.ObjectTest.testDeleteObject(ObjectTest.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteObject -->
  <testcase classname="com.example.api.ObjectTest" name="testGetAllObjects" time="0.873"/>
</testsuite> <!-- Surefire test -->
